### ISSUE TITLE
I lack some necessary DLLs

### ISSUE THREAD

**Issue by Chenshuai770** [shtirlitsDva/MyRevitAddins#15]
Hello, thank you very much for the open source Revit plug-in code. I am a novice developer of Revit, and I am currently studying your project. But when I imported the project, I lacked some necessary dll. I don't know where to find it. I don't know if I can provide some ideas or download the website with dll. The following picture is my missing dll.

mg.revit-shared-utilities.dll
Microsoft.CSharp.dll
Microsoft.WindowsAPICodePack.dll
Microsoft.WindowsAPICodePack.ExtendedLinguisticServices.dll
Microsoft.WindowsAPICodePack.Sensors.dll
Microsoft.WindowsAPICodePack.Shell.dll
Microsoft.WindowsAPICodePack.ShellExtensions.dll
System.ValueTuple.dll

**Comment by shtirlitsDva** [comment]
Hi
If you use Visual Studio, you should push the build button and all those .dlls should be installed by the Nuget package manager. All of them are Nuget packages except CSharp.dll, which should already be present in your installation of Visual Studio.

**Comment by Chenshuai770** [comment]
Thank you for answering my question. I have found a way to solve the problem.
On this website, https://www.nuget.org/packages/ can download the DL I need to download. I have successfully compiled your project, but when I applied it to Revit, I found it impossible to use it.
This is the MyRevitAddins. addin file. Do ClientId need to be replaced
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<RevitAddIns>
   <AddIn Type="Application">
      <Assembly>C:\ProgramData\Autodesk\Revit\Addins\2018\icon\MyRibbonPanel.dll</Assembly>
      <ClientId>973C4F18-300B-41A4-A998-C289820D1969</ClientId>
      <FullClassName>MyRibbonPanel.App</FullClassName>
      <Name>MyAddIns</Name>
      <VendorId>MGTek</VendorId>
      <VendorDescription>app@mgtek.dk</VendorDescription>	  
   </AddIn>
</RevitAddIns>
Here is a screenshot of the specific problem. 
https://quaer.oss-cn-hangzhou.aliyuncs.com/app/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190401142441.png

**Comment by Chenshuai770** [comment]
Thank you for answering my question. I have found a way to solve the problem.
On this website, https://www.nuget.org/packages/ can download the DL I need to download. I have successfully compiled your project, but when I applied it to Revit, I found it impossible to use it.
This is the MyRevitAddins. addin file. Do ClientId need to be replaced
`
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<RevitAddIns>
   <AddIn Type="Application">
      <Assembly>C:\ProgramData\Autodesk\Revit\Addins\2018\icon\MyRibbonPanel.dll</Assembly>
      <ClientId>973C4F18-300B-41A4-A998-C289820D1969</ClientId>
      <FullClassName>MyRibbonPanel.App</FullClassName>
      <Name>MyAddIns</Name>
      <VendorId>MGTek</VendorId>
      <VendorDescription>app@mgtek.dk</VendorDescription>	  
   </AddIn>
</RevitAddIns>
`
Here is a screenshot of the specific problem
[https://quaer.oss-cn-hangzhou.aliyuncs.com/app/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190401142441.png](url)

**Comment by shtirlitsDva** [comment]
Hi
No client id needs not be changed unless you already have another add-in with the same id, which is unlikely.
Regarding the error, it seems that not all add-in dlls are copied to the add-in folder.
The add-in creates additional .dll. They all are placed in the bin/Release folder when compiled. If the compilation is successful, then you have to copy EVERYTHING in the Release folder to the add-in folder.

**Comment by Chenshuai770** [comment]
Thank you for your reply, but I still failed to run successfully; I used the 2018 version of SDK, mg. revit-shared-utilities. dll may not run, I am a novice Revit developer, I need some suggestions to learn Revit secondary development, can provide some learning path methods or blog, thank you very much.

**Comment by shtirlitsDva** [comment]
Try the official site first :
https://www.autodesk.com/developer-network/platform-technologies/revit
